= OpenSCAP User Manual
:imagesdir: ./images
:toc:

image::vertical-logo.svg[align="center"]

== What is SCAP

The SCAP (Security Certification and Authorization Package) is a line of specifications maintained by the NIST (National Institute of Standards and Technology) for maintaining system security for enterprise systems.

SCAP was created to provide a standardized approach to maintaining system security, and the standards that are used will therefore continually change to meet the needs of the community and enterprise businesses. New specifications are governed by NIST's SCAP Release cycle in order to provide a consistent and repeatable revision workflow. 

== What is OpenSCAP

OpenSCAP checks system security configuration settings, and examines systems for signs of compromise by using rules based on standards and specifications.

OpenSCAP is an auditing tool that utilizes the XCCDF (Extensible Configuration Checklist Description Format) what is a standard way of expressing checklist content and defines security checklists. It also combines with other specifications such as CPE (Common Platform Enumeration), CCE (Common Configuration Enumeration), OVAL (Open Vulnerability and Assessment Language) to create a SCAP-expressed checklist that can be processed by SCAP-validated products.


== Prerequisities for OpenSCAP

To effectively use OpenSCAP, the following must be available::

 . A tool (to verify that a system conforms to a standard)
 . Satellite Server 5.5 and later use OpenSCAP as an auditing feature
 . SCAP content


== OSCAP Command Line

The *oscap* is a command line tool that allows users to load, scan, validate, edit and export SCAP documents. Its alternative is SCAP Workbench GUI.

=== Common OSCAP Operations

For information about oscap capabilities and complete list of options, refer to the oscap manual pages:

 $ man oscap

=== Using OSCAP
Install SCAP Content:: 
Prior using the oscap tool, you have to install SCAP content on your system. You can download the SCAP content from the respective web site or you can install it using a package management system implemented in by your Linux distribution.

Proces the content:: 
When the SCAP content is imported or installed on your system, oscap can process the content by specifying the file pathh to the content. The oscap tool supports SCAP 1.2 and is backward compatible with SCAP 1.1 and 1.0. No special treatment is required in order to import and process earlier versions of the SCAP content.

To display the version of oscap, supported specifications, built-in CPE names and supported OVAL objects:

 $ oscap -V


== SCAP Workbench

*SCAP Workbench* is a GUI application with scanning and tailoring capabilities. Its alternative is oscap command line.

== Creating your own content

You can generate your own SCAP content if you have an understanding of at least XCCDF or OVAL. XCCDF content is also
frequently published online under open source licenses, and you can customize this content to suit your needs instead. 
